### ISSUE TITLE
Feedback 

### ISSUE THREAD

**Issue by HarisSpahija** [ConanSpithoven/PRG-4-Inleveropdracht#1]
**Mechanics**
Op het gebied van mechanics is het vrij eenvoudig. Misschien is het toevoegen van keyboard input een leuk idee voor het vechten van de monsters.

**Code**
Je code is af en toe moeilijk te begrijpen. Vooral in item.ts is het opvallend dat je veel if statements gebruikt. Veel van de statements kun je verwerken in een functie ipv een lijst te maken met mogelijkheden. Dat bespaart code en zorgt ervoor dat de code overzichtelijk is en hergebruikt kan worden. Ook raad ik aan om code comments zoals in startscreen.ts (Line 8-10) opruimt. 
Het is slim dat je wel voor je monsters een removeMe hebt aangemaakt in de child classes. Dit voorkomt eventuele errors met overblijfselen van code. 
Ook maak je slim gebruik van inheritence bij de items en bosses.
Je maakt gebruik van Encapsulation alleen soms voeg je een item toe aan je class die je nooit meer aan roept (Zie **UML**)

**UML**
Je uml is overzichtelijk en netjes geordend. Wel vraag ik me af wat Sscreen doet in je game.ts, je roept namenlijk de sscreen nooit aan in de code. Misschien die uit de UML halen?

**Opinion**
De game is wel grappig maar wordt al erg snel "saai". Wel leuk dat de bosses die je fight geanimeerd zijn. Jammer dat er geen geluid is. Probeer er op te letten minder if statements te gebruiken om verwarring te voorkomen.

**Comment by ConanSpithoven** [comment]
heb de comments opgeruimt en ben aan het kijken naar de UML
